services:
  app:
    build: .
    image: drone-planner
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      redis:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./cache_data:/app/cache_data
      - ./cache:/app/cache
      - ./data:/app/data
    deploy:
      resources:
        limits:
          cpus: '6'

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  redis_data:
